name: com.sleepysquish.blob.SleepyBlob
main: com.sleepysquish.blob.SleepyBlob
version: 1.0
api-version: 1.16
author: sleepysquish
depend: [WorldGuard]
softdepend: [ProtocolLib]

commands:
  sl:
    description: sleepy blob commands
    aliases: _sleepyblob
    permission: sleepyblob.admin
    usage: /sl <etc> <etc>
    permission-message: no. sorry.
  pay:
    description: pay other people orerus
    usage: /pay <player> <amount>
    permission: sleepyblob.common
  money:
    description: how many orerus you have
    usage: /money
    aliases:
      - orerus
    permission: sleepyblob.common
  claim:
    description: /claim - to start claiming, /claim cancel - to cancel claiming, /claim list - to see and delete claims, /claim friend - add friend to all your claims
    usage: /claim - to start claiming, /claim cancel - to cancel claiming, /claim list - to see and delete claims, /claim friend - add friend to all your claims
    permission: sleepyblob.common
  showclaims:
    usage: /showclaims - toggle claim border visibility, /showclaims <id>
    permission: sleepyblob.common
  verify:
    usage: /verify
    permission: sleepyblob.common


permissions:
  sleepyblob.admin:
    description: allows you to do anything with sleepyblob
    default: op
  sleepyblob.common:
    description: for normal people
    default: true
